/**
 * Jules API Client Module
 * 
 * This module handles communication with the Google Jules API for creating agent sessions.
 * 
 * **Security Features:**
 * - Input validation for all parameters
 * - Request timeout (30 seconds)
 * - Sanitized error messages (prevents information disclosure)
 * - Response structure validation
 * 
 * **API Endpoint:**
 * - Base URL: https://jules.googleapis.com/v1alpha/sessions
 * - Authentication: X-Goog-Api-Key header
 * 
 * @module julesClient
 */

import { SecretsManager } from './secrets';
import {
    validateGitHubIdentifier,
    validateBranchName,
    validatePrompt,
    validateSessionResponse
} from './validators';
import {
    ProjectNotInitializedError,
    ApiError,
    TimeoutError,
    ConfigurationError
} from './errors';
import { API_CONFIG, MESSAGES } from './constants';

/**
 * Client for interacting with the Google Jules API.
 * 
 * Handles session creation with comprehensive security validations,
 * timeout protection, and error sanitization.
 */
export class JulesClient {
    constructor(private secrets: SecretsManager) { }

    /**
     * Create a new Jules session for the given repository and prompt.
     * 
     * This method performs comprehensive input validation and security checks:
     * 1. Validates all inputs (owner, repo, branch, prompt)
     * 2. Ensures API key is available
     * 3. Makes API request with timeout protection
     * 4. Validates response structure
     * 5. Sanitizes errors before throwing
     * 
     * @param owner - GitHub repository owner
     * @param repo - GitHub repository name
     * @param branch - Starting branch name
     * @param prompt - Context-aware prompt generated by PromptGenerator
     * @returns JulesSession object with session name and ID
     * @throws ValidationError if inputs are invalid
     * @throws ProjectNotInitializedError if repository is not initialized in Jules
     * @throws ApiError for API errors (with sanitized messages)
     * @throws TimeoutError if request times out
     * @throws ConfigurationError if API key is missing
     * 
     * @example
     * ```typescript
     * const session = await julesClient.createSession(
     *   'google',
     *   'jules',
     *   'main',
     *   'Implement user authentication'
     * );
     * console.log(`Session created: ${session.id}`);
     * // Visit: https://jules.google.com/sessions/{session.id}
     * ```
     */
    async createSession(
        owner: string,
        repo: string,
        branch: string,
        prompt: string
    ): Promise<JulesSession> {
        // 1. SECURITY: Validate all inputs before making API call
        validateGitHubIdentifier(owner, 'owner');
        validateGitHubIdentifier(repo, 'repo');
        validateBranchName(branch);
        validatePrompt(prompt);

        // 2. Get and validate API key
        let apiKey = await this.secrets.getKey();
        if (!apiKey) {
            apiKey = await this.secrets.promptAndStoreKey();
            if (!apiKey) {
                throw new ConfigurationError(MESSAGES.API_KEY_REQUIRED, 'apiKey');
            }
        }

        // 3. Prepare request payload
        const payload = {
            prompt: prompt.trim(),
            sourceContext: {
                source: `sources/github/${owner}/${repo}`,
                githubRepoContext: { startingBranch: branch }
            },
            title: `Auto-Handoff: ${new Date().toLocaleTimeString()}`
        };

        // 4. SECURITY: Add request timeout to prevent hanging
        const controller = new AbortController();
        const timeoutId = setTimeout(() => controller.abort(), API_CONFIG.TIMEOUT_MS);

        try {
            // 5. Make API request
            const response = await fetch(API_CONFIG.BASE_URL, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-Goog-Api-Key': apiKey
                },
                body: JSON.stringify(payload),
                signal: controller.signal
            });

            clearTimeout(timeoutId);

            // 6. Handle API errors securely
            if (!response.ok) {
                const errorText = await response.text();

                // Special handling for repository not initialized
                if (response.status === 404 && errorText.includes("Requested entity was not found")) {
                    throw new ProjectNotInitializedError(owner, repo);
                }

                // SECURITY: Sanitize error message before throwing
                const sanitizedError = this.sanitizeApiError(errorText, response.status);
                throw new ApiError(sanitizedError, response.status, errorText);
            }

            // 7. Parse and validate response
            const responseData = await response.json();

            // SECURITY: Validate response structure to prevent malformed data
            validateSessionResponse(responseData);

            return responseData as JulesSession;

        } catch (error: any) {
            clearTimeout(timeoutId);

            // Handle timeout errors specially
            if (error.name === 'AbortError') {
                throw new TimeoutError(
                    'Request to Jules API timed out. Please check your network connection.',
                    API_CONFIG.TIMEOUT_MS
                );
            }

            // Re-throw our custom errors as-is
            if (error instanceof ProjectNotInitializedError ||
                error instanceof ApiError ||
                error instanceof TimeoutError ||
                error instanceof ConfigurationError) {
                throw error;
            }

            // Wrap unexpected errors
            throw new ApiError(
                'An unexpected error occurred while creating Jules session',
                undefined,
                error.message
            );
        }
    }

    /**
     * Sanitize API error messages to prevent information disclosure.
     * 
     * Raw API errors may contain sensitive information like:
     * - Internal server paths
     * - Database details
     * - API keys
     * - User IDs
     * 
     * This method returns user-friendly generic messages.
     * 
     * @param errorText - Raw error text from API
     * @param statusCode - HTTP status code
     * @returns Sanitized, user-friendly error message
     * @private
     */
    private sanitizeApiError(errorText: string, statusCode: number): string {
        // SECURITY: Never show raw error to user - could contain sensitive data
        const genericErrors: Record<number, string> = {
            400: 'Invalid request. Please check your repository configuration.',
            401: 'Authentication failed. Please verify your API key.',
            403: 'Access denied. Check your Jules permissions.',
            404: 'Repository not found in Jules.',
            429: 'Rate limit exceeded. Please try again later.',
            500: 'Jules API error. Please try again.',
            503: 'Jules service is temporarily unavailable.'
        };

        return genericErrors[statusCode] || `API request failed with status ${statusCode}`;
    }
}

/**
 * Response object from Jules API session creation.
 * 
 * Contains identifiers for tracking and accessing the created session.
 */
export interface JulesSession {
    /** Display name of the session (e.g., "Auto-Handoff: 10:30:45 AM") */
    name: string;
    /** Unique session identifier used in dashboard URLs */
    id: string;
}
