/**
 * Jules API Client Module
 * 
 * This module handles communication with the Google Jules API for creating agent sessions.
 * 
 * **API Endpoint:**
 * - Base URL: https://jules.googleapis.com/v1alpha/sessions
 * - Authentication: X-Goog-Api-Key header
 * 
 * **Error Handling:**
 * - 404 errors are checked for "Requested entity was not found" to detect
 *   repositories not initialized in Jules (requires GitHub App installation)
 * 
 * @module julesClient
 */

import { SecretsManager } from './secrets';

/**
 * Custom error thrown when a GitHub repository is not initialized in Jules.
 * 
 * This error indicates that the Jules GitHub App needs to be installed
 * and configured for the repository.
 */
export class ProjectNotInitializedError extends Error {
    /**
     * Creates a ProjectNotInitializedError.
     * 
     * @param owner - GitHub repository owner
     * @param repo - GitHub repository name
     */
    constructor(public owner: string, public repo: string) {
        super(`Project ${owner}/${repo} not initialized in Jules.`);
        this.name = 'ProjectNotInitializedError';
    }
}

/**
 * Client for interacting with the Google Jules API.
 * 
 * Handles session creation with automatic API key management and error handling.
 */
export class JulesClient {
    constructor(private secrets: SecretsManager) { }

    /**
     * Create a new Jules session for the given repository and prompt.
     * 
     * The session is created with the following context:
     * - GitHub repository source (`sources/github/{owner}/{repo}`)
     * - Starting branch
     * - User prompt with workspace context
     * 
     * @param owner - GitHub repository owner
     * @param repo - GitHub repository name
     * @param branch - Starting branch name
     * @param prompt - Context-aware prompt generated by PromptGenerator
     * @returns JulesSession object with session name and ID
     * @throws ProjectNotInitializedError if repository is not initialized in Jules
     * @throws Error for other API errors
     * 
     * @example
     * ```typescript
     * const session = await julesClient.createSession(
     *   'google',
     *   'jules',
     *   'main',
     *   'Implement user authentication'
     * );
     * console.log(`Session created: ${session.id}`);
     * // Visit: https://jules.google.com/sessions/{session.id}
     * ```
     */
    async createSession(owner: string, repo: string, branch: string, prompt: string): Promise<JulesSession> {
        let apiKey = await this.secrets.getKey();
        if (!apiKey) {
            // Prompt if missing during execution
            apiKey = await this.secrets.promptAndStoreKey();
            if (!apiKey) throw new Error("API Key required.");
        }

        const payload = {
            prompt: prompt,
            sourceContext: {
                source: `sources/github/${owner}/${repo}`,
                githubRepoContext: { startingBranch: branch }
            },
            title: `Auto-Handoff: ${new Date().toLocaleTimeString()}`
        };

        // Using global fetch (Node 18+ / VS Code)
        const response = await fetch('https://jules.googleapis.com/v1alpha/sessions', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-Goog-Api-Key': apiKey
            },
            body: JSON.stringify(payload)
        });

        if (!response.ok) {
            if (response.status === 404) {
                // Check if it's the "Requested entity was not found" error
                const errorText = await response.text();
                if (errorText.includes("Requested entity was not found")) {
                    throw new ProjectNotInitializedError(owner, repo);
                }
                throw new Error(`API Error ${response.status}: ${errorText}`);
            }
            throw new Error(`API Error ${response.status}: ${await response.text()}`);
        }

        return await response.json() as JulesSession;
    }
}

/**
 * Response object from Jules API session creation.
 * 
 * Contains identifiers for tracking and accessing the created session.
 */
export interface JulesSession {
    /** Display name of the session (e.g., "Auto-Handoff: 10:30:45 AM") */
    name: string;
    /** Unique session identifier used in dashboard URLs */
    id: string;
}
